export const ACCOUNT_DATA_RIGHTS_REPOSITORY = Symbol(
  "ACCOUNT_DATA_RIGHTS_REPOSITORY"
);
export const ACCOUNT_SCOPE_RUNTIME_COORDINATOR = Symbol(
  "ACCOUNT_SCOPE_RUNTIME_COORDINATOR"
);
export const ACCOUNT_SCOPE_HASHER = Symbol("ACCOUNT_SCOPE_HASHER");
export const ACCOUNT_DELETION_STATUS_COOKIES = Symbol(
  "ACCOUNT_DELETION_STATUS_COOKIES"
);
export const ACCOUNT_SYSTEM_DATABASE = Symbol("ACCOUNT_SYSTEM_DATABASE");
export const ACCOUNT_DELETION_FRESH_AUTHORITY = Symbol(
  "ACCOUNT_DELETION_FRESH_AUTHORITY"
);
